# Generated by Django 5.2.5 on 2025-08-14 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(
                    max_length=254,
                    unique=True,
                    verbose_name='Эл. почта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('bio', models.TextField(
                    blank=True,
                    verbose_name='Биография')
                 ),
                ('birth_date', models.DateField(
                    blank=True, null=True,
                    verbose_name='Дата рождения')
                 ),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='user.user',
                    verbose_name='Пользователь')
                 ),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
